language: node_js
node_js:
  - "8.15.1"
services:
  - mongodb
script:
  - npm test

notifications:
  email:
    recipients:
      - a.redonda89@gmail.com
      - miloromiguel@gmail.com
      - nadiavanina@gmail.com
    on_success: never # default: change
    on_failure: always # default: always